//
//  SeedWords.swift
//  GRE Words Quizzes
//
//  The local, offline GRE vocabulary bank that ships with the app.
//  Each entry carries a definition and a "characteristic" description
//  (features / use / color / shape / connotation) so that three
//  distinct hint dimensions can always be produced even when the
//  on-device language model is unavailable.
//

import Foundation

/// A plain value type describing a single vocabulary entry in the seed bank.
struct SeedWord {
    let word: String
    let partOfSpeech: String
    /// Dimension A — the meaning / definition of the word.
    let definition: String
    /// Dimension C — concrete features, typical use, connotation, shape, etc.
    let characteristic: String
}

enum SeedWords {
    /// The starter GRE word bank. This is intentionally curated so every
    /// word has a rich, spoken-friendly definition and a distinct
    /// characteristic clue.
    static let all: [SeedWord] = [
        SeedWord(word: "abate",
                 partOfSpeech: "verb",
                 definition: "to become less intense or widespread; to reduce in amount or degree",
                 characteristic: "Think of a storm calming down or a fever dropping. It describes something powerful gradually fading away."),
        SeedWord(word: "aberration",
                 partOfSpeech: "noun",
                 definition: "a departure from what is normal, usual, or expected, typically unwelcome",
                 characteristic: "It is the odd one out, a strange glitch that does not fit the pattern of everything around it."),
        SeedWord(word: "abscond",
                 partOfSpeech: "verb",
                 definition: "to leave hurriedly and secretly, typically to avoid detection or arrest",
                 characteristic: "Picture a thief sneaking away in the night with the stolen money before anyone notices."),
        SeedWord(word: "alacrity",
                 partOfSpeech: "noun",
                 definition: "brisk and cheerful readiness; eager and prompt willingness",
                 characteristic: "It is the bright, springy energy of someone who jumps up to help the very second they are asked."),
        SeedWord(word: "anomaly",
                 partOfSpeech: "noun",
                 definition: "something that deviates from what is standard, normal, or expected",
                 characteristic: "Scientists use it for a strange reading on an instrument that breaks the usual rule."),
        SeedWord(word: "antipathy",
                 partOfSpeech: "noun",
                 definition: "a deep-seated feeling of dislike or aversion",
                 characteristic: "It is a cold, strong feeling of distaste, the opposite of warmth and affection toward someone."),
        SeedWord(word: "approbation",
                 partOfSpeech: "noun",
                 definition: "approval or praise, especially when given officially",
                 characteristic: "Think of a nod of formal approval, a stamp of warm official praise from those in charge."),
        SeedWord(word: "arduous",
                 partOfSpeech: "adjective",
                 definition: "involving or requiring strenuous and prolonged effort; very difficult and tiring",
                 characteristic: "Imagine a long, steep mountain climb that leaves you exhausted and drenched in sweat."),
        SeedWord(word: "audacious",
                 partOfSpeech: "adjective",
                 definition: "showing a willingness to take surprisingly bold risks; daring",
                 characteristic: "It describes a fearless, cheeky boldness, like a daredevil attempting an impossible stunt."),
        SeedWord(word: "austere",
                 partOfSpeech: "adjective",
                 definition: "severe or strict in manner or appearance; having no comforts or luxuries",
                 characteristic: "Picture a bare gray room with a single hard chair, plain and stripped of all decoration."),
        SeedWord(word: "belie",
                 partOfSpeech: "verb",
                 definition: "to fail to give a true impression of something; to contradict",
                 characteristic: "It is a calm face that hides a storm inside, an appearance that disguises the real truth."),
        SeedWord(word: "benevolent",
                 partOfSpeech: "adjective",
                 definition: "well meaning and kindly; generous in spirit",
                 characteristic: "Think of a warm, generous person who gives freely and wishes good things for everyone."),
        SeedWord(word: "bolster",
                 partOfSpeech: "verb",
                 definition: "to support, strengthen, or reinforce",
                 characteristic: "Like propping up a wall with a sturdy beam, it props up an argument or someone's confidence."),
        SeedWord(word: "cacophony",
                 partOfSpeech: "noun",
                 definition: "a harsh, discordant mixture of sounds",
                 characteristic: "Imagine car horns, drills, and shouting all clashing at once into ugly, jarring noise."),
        SeedWord(word: "candor",
                 partOfSpeech: "noun",
                 definition: "the quality of being open, honest, and direct in expression",
                 characteristic: "It is clear, plain truth-telling, with no sugar-coating and nothing hidden behind politeness."),
        SeedWord(word: "capricious",
                 partOfSpeech: "adjective",
                 definition: "given to sudden and unaccountable changes of mood or behavior",
                 characteristic: "Think of the weather that switches from sunshine to rain on a whim, unpredictable and flighty."),
        SeedWord(word: "censure",
                 partOfSpeech: "verb",
                 definition: "to express severe or formal disapproval of someone or something",
                 characteristic: "It is an official scolding, a stern public reprimand handed down for wrongdoing."),
        SeedWord(word: "circumspect",
                 partOfSpeech: "adjective",
                 definition: "wary and unwilling to take risks; cautious",
                 characteristic: "Picture someone looking carefully in every direction before stepping forward, watchful and prudent."),
        SeedWord(word: "clandestine",
                 partOfSpeech: "adjective",
                 definition: "kept secret or done secretively, especially because illicit",
                 characteristic: "Think of a hidden meeting in a dark basement, conducted quietly so no one finds out."),
        SeedWord(word: "cogent",
                 partOfSpeech: "adjective",
                 definition: "clear, logical, and convincing",
                 characteristic: "It describes an argument so tightly reasoned and persuasive that it is hard to disagree with."),
        SeedWord(word: "complacent",
                 partOfSpeech: "adjective",
                 definition: "showing smug or uncritical satisfaction with oneself or one's achievements",
                 characteristic: "Picture someone leaning back, too pleased with themselves to notice trouble approaching."),
        SeedWord(word: "conflagration",
                 partOfSpeech: "noun",
                 definition: "an extensive and destructive fire",
                 characteristic: "Imagine a massive blaze with towering orange flames swallowing an entire building or forest."),
        SeedWord(word: "convoluted",
                 partOfSpeech: "adjective",
                 definition: "extremely complex and difficult to follow",
                 characteristic: "Think of a tangled knot of twisting paths, a plot with so many turns you lose track."),
        SeedWord(word: "deference",
                 partOfSpeech: "noun",
                 definition: "humble submission and respect; yielding to the opinion of another",
                 characteristic: "It is the polite bow of respect, stepping aside to honor someone's authority or judgment."),
        SeedWord(word: "deleterious",
                 partOfSpeech: "adjective",
                 definition: "causing harm or damage",
                 characteristic: "Think of a toxic substance that slowly and quietly damages your health over time."),
        SeedWord(word: "diatribe",
                 partOfSpeech: "noun",
                 definition: "a forceful and bitter verbal attack against someone or something",
                 characteristic: "Picture a long, angry rant, a furious speech pouring out harsh criticism without pause."),
        SeedWord(word: "diffident",
                 partOfSpeech: "adjective",
                 definition: "modest or shy because of a lack of self-confidence",
                 characteristic: "Imagine someone hanging back at the edge of a room, hesitant and unsure of themselves."),
        SeedWord(word: "dilatory",
                 partOfSpeech: "adjective",
                 definition: "slow to act; intended to cause delay",
                 characteristic: "Think of someone dragging their feet, stalling and putting things off again and again."),
        SeedWord(word: "disparage",
                 partOfSpeech: "verb",
                 definition: "to regard or represent as being of little worth; to belittle",
                 characteristic: "It is talking someone down, mocking their efforts to make them seem small and unimportant."),
        SeedWord(word: "dogmatic",
                 partOfSpeech: "adjective",
                 definition: "inclined to lay down principles as undeniably true, allowing no debate",
                 characteristic: "Picture a rigid person insisting they are right and flatly refusing to consider any other view."),
        SeedWord(word: "ebullient",
                 partOfSpeech: "adjective",
                 definition: "cheerful and full of energy; overflowing with enthusiasm",
                 characteristic: "Think of bubbles fizzing up out of soda, a person bursting with bright, lively excitement."),
        SeedWord(word: "eclectic",
                 partOfSpeech: "adjective",
                 definition: "deriving ideas or style from a broad and diverse range of sources",
                 characteristic: "Imagine a playlist mixing jazz, hip-hop, and classical, a colorful blend drawn from many styles."),
        SeedWord(word: "egregious",
                 partOfSpeech: "adjective",
                 definition: "outstandingly bad; shocking",
                 characteristic: "It describes a mistake so glaringly awful that everyone notices it immediately."),
        SeedWord(word: "eloquent",
                 partOfSpeech: "adjective",
                 definition: "fluent or persuasive in speaking or writing",
                 characteristic: "Picture a speaker whose graceful, flowing words move the whole audience to tears or cheers."),
        SeedWord(word: "enervate",
                 partOfSpeech: "verb",
                 definition: "to cause someone to feel drained of energy or vitality; to weaken",
                 characteristic: "Think of a long heatwave that leaves you limp, tired, and completely sapped of strength."),
        SeedWord(word: "ephemeral",
                 partOfSpeech: "adjective",
                 definition: "lasting for a very short time",
                 characteristic: "Like a mayfly that lives a single day, or a snowflake that melts the instant it lands."),
        SeedWord(word: "equivocate",
                 partOfSpeech: "verb",
                 definition: "to use ambiguous language so as to conceal the truth or avoid commitment",
                 characteristic: "Picture a politician giving slippery, vague answers to dodge a yes-or-no question."),
        SeedWord(word: "erudite",
                 partOfSpeech: "adjective",
                 definition: "having or showing great knowledge gained from study; scholarly",
                 characteristic: "Think of a learned professor surrounded by books, deeply read on many subjects."),
        SeedWord(word: "exacerbate",
                 partOfSpeech: "verb",
                 definition: "to make a problem, bad situation, or negative feeling worse",
                 characteristic: "Like scratching an itchy rash, it takes something bad and makes it even worse."),
        SeedWord(word: "fastidious",
                 partOfSpeech: "adjective",
                 definition: "very attentive to and concerned about accuracy and detail; hard to please",
                 characteristic: "Picture someone wiping every speck of dust, fussy and exacting about the smallest detail."),
        SeedWord(word: "fervent",
                 partOfSpeech: "adjective",
                 definition: "having or displaying a passionate intensity",
                 characteristic: "Think of a glowing, hot devotion, a believer whose feelings burn with passion."),
        SeedWord(word: "frugal",
                 partOfSpeech: "adjective",
                 definition: "sparing or economical with regard to money or food; thrifty",
                 characteristic: "Picture someone who saves every coin, reuses leftovers, and avoids any wasteful spending."),
        SeedWord(word: "garrulous",
                 partOfSpeech: "adjective",
                 definition: "excessively talkative, especially on trivial matters",
                 characteristic: "Think of a chatterbox who talks endlessly about nothing and never seems to pause for breath."),
        SeedWord(word: "gregarious",
                 partOfSpeech: "adjective",
                 definition: "fond of company; sociable",
                 characteristic: "Picture the life of the party, someone who thrives in a crowd and loves being around people."),
        SeedWord(word: "hackneyed",
                 partOfSpeech: "adjective",
                 definition: "lacking significance through having been overused; unoriginal and trite",
                 characteristic: "Think of a worn-out cliche you have heard a thousand times, stale and predictable."),
        SeedWord(word: "iconoclast",
                 partOfSpeech: "noun",
                 definition: "a person who attacks cherished beliefs or established institutions",
                 characteristic: "Picture a rebel smashing old idols, someone who challenges traditions everyone else accepts."),
        SeedWord(word: "impecunious",
                 partOfSpeech: "adjective",
                 definition: "having little or no money; penniless",
                 characteristic: "Think of empty pockets and a thin wallet, someone who is broke and cannot pay the bills."),
        SeedWord(word: "inchoate",
                 partOfSpeech: "adjective",
                 definition: "just begun and so not fully formed or developed; rudimentary",
                 characteristic: "Like a vague idea still taking shape, a sketch that is barely started and undefined."),
        SeedWord(word: "ineffable",
                 partOfSpeech: "adjective",
                 definition: "too great or extreme to be expressed or described in words",
                 characteristic: "Think of a feeling of awe so overwhelming that no words could ever capture it."),
        SeedWord(word: "insipid",
                 partOfSpeech: "adjective",
                 definition: "lacking flavor, vigor, or interest; dull",
                 characteristic: "Picture a bowl of watery, flavorless soup, or a boring movie with no spark at all."),
        SeedWord(word: "intransigent",
                 partOfSpeech: "adjective",
                 definition: "unwilling or refusing to change one's views or to agree about something",
                 characteristic: "Think of a stubborn negotiator planted like a rock who will not budge an inch."),
        SeedWord(word: "laconic",
                 partOfSpeech: "adjective",
                 definition: "using very few words; terse",
                 characteristic: "Picture a quiet cowboy who answers a long question with a single short word."),
        SeedWord(word: "laud",
                 partOfSpeech: "verb",
                 definition: "to praise highly, especially in a public context",
                 characteristic: "Think of a crowd cheering and showering a hero with glowing public praise."),
        SeedWord(word: "lethargic",
                 partOfSpeech: "adjective",
                 definition: "affected by tiredness and a lack of energy; sluggish",
                 characteristic: "Picture someone slumped on a couch, heavy-eyed and too drowsy to move."),
        SeedWord(word: "loquacious",
                 partOfSpeech: "adjective",
                 definition: "tending to talk a great deal; very talkative",
                 characteristic: "Think of someone who never stops chatting, filling every silence with a flood of words."),
        SeedWord(word: "magnanimous",
                 partOfSpeech: "adjective",
                 definition: "very generous or forgiving, especially toward a rival or less powerful person",
                 characteristic: "Picture a champion who graciously praises the opponent they just defeated."),
        SeedWord(word: "mitigate",
                 partOfSpeech: "verb",
                 definition: "to make less severe, serious, or painful",
                 characteristic: "Like a cushion softening a fall, it eases and lessens something harmful."),
        SeedWord(word: "mundane",
                 partOfSpeech: "adjective",
                 definition: "lacking interest or excitement; dull and ordinary",
                 characteristic: "Think of the gray routine of everyday chores, plain, common, and unremarkable."),
        SeedWord(word: "nefarious",
                 partOfSpeech: "adjective",
                 definition: "wicked or criminal; extremely evil",
                 characteristic: "Picture a villain twirling a mustache while plotting a dark, sinister scheme."),
        SeedWord(word: "obfuscate",
                 partOfSpeech: "verb",
                 definition: "to render obscure, unclear, or unintelligible; to confuse deliberately",
                 characteristic: "Like throwing a fog over the facts, it muddies the water so the truth is hard to see."),
        SeedWord(word: "obsequious",
                 partOfSpeech: "adjective",
                 definition: "obedient or attentive to an excessive or servile degree",
                 characteristic: "Think of a flatterer bowing and fawning, desperately eager to please the boss."),
        SeedWord(word: "ostentatious",
                 partOfSpeech: "adjective",
                 definition: "characterized by vulgar or pretentious display; designed to impress",
                 characteristic: "Picture a flashy gold car and dripping jewelry, showing off wealth to impress everyone."),
        SeedWord(word: "paradigm",
                 partOfSpeech: "noun",
                 definition: "a typical example or pattern of something; a model",
                 characteristic: "Think of the master blueprint or framework that everything else is modeled after."),
        SeedWord(word: "pejorative",
                 partOfSpeech: "adjective",
                 definition: "expressing contempt or disapproval",
                 characteristic: "It describes an insulting word chosen to put someone down and show scorn."),
        SeedWord(word: "perfunctory",
                 partOfSpeech: "adjective",
                 definition: "carried out with a minimum of effort or reflection; cursory",
                 characteristic: "Picture a quick, careless handshake done just to get it over with, with no real interest."),
        SeedWord(word: "pernicious",
                 partOfSpeech: "adjective",
                 definition: "having a harmful effect, especially in a gradual or subtle way",
                 characteristic: "Think of a quiet poison or a creeping rumor that slowly destroys from within."),
        SeedWord(word: "phlegmatic",
                 partOfSpeech: "adjective",
                 definition: "having an unemotional and stolidly calm disposition",
                 characteristic: "Picture someone utterly unruffled, staying cool and calm even in a crisis."),
        SeedWord(word: "placate",
                 partOfSpeech: "verb",
                 definition: "to make someone less angry or hostile; to soothe",
                 characteristic: "Like offering a crying child a toy, it calms an upset person and smooths things over."),
        SeedWord(word: "platitude",
                 partOfSpeech: "noun",
                 definition: "a remark or statement that is overused and lacks originality",
                 characteristic: "Think of a tired saying like 'everything happens for a reason,' flat and meaningless from overuse."),
        SeedWord(word: "pragmatic",
                 partOfSpeech: "adjective",
                 definition: "dealing with things sensibly and realistically; practical",
                 characteristic: "Picture a no-nonsense problem solver who cares about what actually works, not theory."),
        SeedWord(word: "preclude",
                 partOfSpeech: "verb",
                 definition: "to prevent something from happening; to make impossible in advance",
                 characteristic: "Like locking a door ahead of time, it shuts off a possibility before it can occur."),
        SeedWord(word: "prodigal",
                 partOfSpeech: "adjective",
                 definition: "spending money or resources freely and recklessly; wastefully extravagant",
                 characteristic: "Think of someone burning through a fortune on luxuries until nothing is left."),
        SeedWord(word: "proliferate",
                 partOfSpeech: "verb",
                 definition: "to increase rapidly in numbers; to multiply",
                 characteristic: "Picture cells dividing or rabbits multiplying, spreading and growing fast everywhere."),
        SeedWord(word: "prosaic",
                 partOfSpeech: "adjective",
                 definition: "having the style or diction of prose; commonplace and unromantic",
                 characteristic: "Think of plain, flat everyday language with no poetry or sparkle to it."),
        SeedWord(word: "quixotic",
                 partOfSpeech: "adjective",
                 definition: "exceedingly idealistic; unrealistic and impractical",
                 characteristic: "Picture a dreamer charging at windmills, chasing noble but hopeless and impractical goals."),
        SeedWord(word: "recalcitrant",
                 partOfSpeech: "adjective",
                 definition: "having an obstinately uncooperative attitude toward authority",
                 characteristic: "Think of a stubborn mule that digs in its heels and refuses every command."),
        SeedWord(word: "reticent",
                 partOfSpeech: "adjective",
                 definition: "not revealing one's thoughts or feelings readily; reserved",
                 characteristic: "Picture a quiet, guarded person who keeps their feelings locked away and says little."),
        SeedWord(word: "sanguine",
                 partOfSpeech: "adjective",
                 definition: "optimistic or positive, especially in an apparently bad or difficult situation",
                 characteristic: "Think of a cheerful, hopeful person who expects the best even when things look grim."),
        SeedWord(word: "sardonic",
                 partOfSpeech: "adjective",
                 definition: "grimly mocking or cynical",
                 characteristic: "Picture a bitter half-smile paired with a sharp, sneering, sarcastic remark."),
        SeedWord(word: "soporific",
                 partOfSpeech: "adjective",
                 definition: "tending to induce drowsiness or sleep",
                 characteristic: "Think of a droning lecture or warm milk that makes your eyelids grow heavy."),
        SeedWord(word: "spurious",
                 partOfSpeech: "adjective",
                 definition: "not being what it purports to be; false or fake",
                 characteristic: "Picture a counterfeit bill or a phony claim that looks real but is completely fake."),
        SeedWord(word: "squander",
                 partOfSpeech: "verb",
                 definition: "to waste something in a reckless and foolish manner",
                 characteristic: "Think of pouring money down the drain or throwing away a golden opportunity."),
        SeedWord(word: "superfluous",
                 partOfSpeech: "adjective",
                 definition: "unnecessary, especially through being more than enough",
                 characteristic: "Like a fifth wheel on a car, it is extra and not needed at all."),
        SeedWord(word: "taciturn",
                 partOfSpeech: "adjective",
                 definition: "reserved or uncommunicative in speech; saying little",
                 characteristic: "Picture a silent, stone-faced person who rarely speaks and keeps to themselves."),
        SeedWord(word: "tenacious",
                 partOfSpeech: "adjective",
                 definition: "tending to keep a firm hold of something; persistent and determined",
                 characteristic: "Think of a bulldog gripping a bone, refusing to let go no matter what."),
        SeedWord(word: "transient",
                 partOfSpeech: "adjective",
                 definition: "lasting only for a short time; impermanent",
                 characteristic: "Like a passing traveler or a fleeting moment, here briefly and then gone."),
        SeedWord(word: "ubiquitous",
                 partOfSpeech: "adjective",
                 definition: "present, appearing, or found everywhere",
                 characteristic: "Think of smartphones or air, seemingly everywhere you look, all the time."),
        SeedWord(word: "venerate",
                 partOfSpeech: "verb",
                 definition: "to regard with great respect; to revere",
                 characteristic: "Picture people bowing before a wise elder or a sacred shrine with deep respect."),
        SeedWord(word: "verbose",
                 partOfSpeech: "adjective",
                 definition: "using or expressed in more words than are needed; wordy",
                 characteristic: "Think of a rambling essay that takes three pages to say one simple thing."),
        SeedWord(word: "vilify",
                 partOfSpeech: "verb",
                 definition: "to speak or write about someone in an abusively disparaging manner",
                 characteristic: "Picture a smear campaign painting a person as evil to ruin their good name."),
        SeedWord(word: "wary",
                 partOfSpeech: "adjective",
                 definition: "feeling or showing caution about possible dangers or problems",
                 characteristic: "Think of a cat eyeing a stranger, alert, careful, and ready to back away."),
        SeedWord(word: "zealous",
                 partOfSpeech: "adjective",
                 definition: "having or showing great energy or enthusiasm in pursuit of a cause",
                 characteristic: "Picture a fired-up volunteer working tirelessly with fierce devotion to their mission.")
    ]
}
